=== Catfeeds/goodwxapp/treasure_national-master/src/app.bundle/View.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <!-- common type defines -->
    <xs:simpleType name="Boolean">
        <xs:restriction base="xs:string">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="InputType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="text"/>
            <xs:enumeration value="number"/>
            <xs:enumeration value="password"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Color">
        <xs:restriction base="xs:string">
            <xs:pattern value="(\#[a-zA-Z0-9]{6}|\#[a-zA-Z0-9]{8})"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Number">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[\-]?[0-9]+(\.[0-9]+)?(dp|px)"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:double">
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>

    <xs:simpleType name="PXNumber">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[\-]?[0-9]+(\.[0-9]+)?px"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>

    <xs:simpleType name="Gravity">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="left"/>
                    <xs:enumeration value="top"/>
                    <xs:enumeration value="right"/>
                    <xs:enumeration value="bottom"/>
                    <xs:enumeration value="center"/>
                    <xs:enumeration value="centerHorizontal"/>
                    <xs:enumeration value="centerVertical"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern
                            value="(left|top|right|bottom|center|centerHorizontal|centerVertical)((\|)(left|top|right|bottom|center|centerHorizontal|centerVertical))+"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>

    </xs:simpleType>
    <xs:simpleType name="TRBLValue">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern
                            value="([\-]?[0-9]+(\.[0-9]+)?(dp|px)?)(\s[\-]?[0-9]+(\.[0-9]+)?(dp|px)?){0,3}"></xs:pattern>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
    <xs:simpleType name="WidthSpecLayoutConstrain">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="WidthLayoutConstrain"/>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern
                            value="(fill|match|wrap|matchHeight|([\-]?[0-9]+(\.[0-9]+)?[dDfF]?))(\s+)([\-]?[0-9]+(\.[0-9]+)?[dDfF]?)"></xs:pattern>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="Number">
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
    <xs:simpleType name="WidthLayoutConstrain">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="fill"/>
                    <xs:enumeration value="match"/>
                    <xs:enumeration value="wrap"/>
                    <xs:enumeration value="matchHeight"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:double">
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
    <xs:simpleType name="HeightSpecLayoutConstrain">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="HeightLayoutConstrain"/>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern
                            value="(fill|match|wrap|matchWidth|([\-]?[0-9]+(\.[0-9]+)?[dDfF]?))(\s+)([\-]?[0-9]+(\.[0-9]+)?[dDfF]?)"></xs:pattern>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
    <xs:simpleType name="HeightLayoutConstrain">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="fill"/>
                    <xs:enumeration value="match"/>
                    <xs:enumeration value="wrap"/>
                    <xs:enumeration value="matchWidth"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:double">
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="Number">
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>


    <xs:simpleType name="LayoutMethod">
        <xs:restriction base="xs:string">
            <xs:enumeration value="frame"/>
            <xs:enumeration value="vertical"/>
            <xs:enumeration value="horizontal"/>
            <xs:enumeration value="flow"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- common attributes -->


    <xs:group name="ViewGroup">
        <xs:choice>
            <xs:element ref="include"/>
            <xs:element ref="View"/>
            <xs:element ref="Page"/>
            <xs:element ref="ScrollView"/>
            <xs:element ref="ImageView"/>
            <xs:element ref="TextView"/>
            <xs:element ref="InputView"/>
            <xs:element ref="TextAreaView"/>
            <xs:element ref="ListView"/>
            <xs:element ref="PullToRefreshView"/>
            <xs:element ref="Button"/>
            <xs:element ref="ToggleButton"/>
            <xs:element ref="ToggleButtonGroup"/>
            <xs:element ref="MapView"/>
            <xs:element ref="WebView"/>
            <xs:element ref="PanoView"/>
            <xs:element ref="ScannerView"/>
            <xs:element ref="Model3DView"/>
        </xs:choice>
    </xs:group>

    <xs:attributeGroup name="ViewAttributes">
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="src" type="xs:string"/>
        <xs:attribute name="alpha" type="xs:float"/>
        <xs:attribute name="anchorX" type="xs:float"/>
        <xs:attribute name="anchorY" type="xs:float"/>
        <xs:attribute name="scaleX" type="xs:float"/>
        <xs:attribute name="scaleY" type="xs:float"/>
        <xs:attribute name="rotateX" type="xs:float"/>
        <xs:attribute name="rotateY" type="xs:float"/>
        <xs:attribute name="rotateZ" type="xs:float"/>
        <xs:attribute name="cameraDistance" type="Number"/>
        <xs:attribute name="visible" type="Boolean"/>
        <xs:attribute name="touchable" type="Boolean"/>
        <xs:attribute name="width" default="fill" type="WidthSpecLayoutConstrain"/>
        <xs:attribute name="height" default="fill" type="HeightSpecLayoutConstrain"/>
        <xs:attribute name="margin" type="TRBLValue"/>
        <xs:attribute name="marginTop" type="Number"/>
        <xs:attribute name="marginRight" type="Number"/>
        <xs:attribute name="marginLeft" type="Number"/>
        <xs:attribute name="marginBottom" type="Number"/>
        <xs:attribute name="padding" type="TRBLValue"/>
        <xs:attribute name="paddingTop" type="Number"/>
        <xs:attribute name="paddingRight" type="Number"/>
        <xs:attribute name="paddingLeft" type="Number"/>
        <xs:attribute name="paddingBottom" type="Number"/>
        <xs:attribute name="gravity" type="Gravity"/>
        <xs:attribute name="contentGravity" type="Gravity"/>
        <xs:attribute name="background" type="Color"/>
        <xs:attribute name="borderWidth" type="Number"/>
        <xs:attribute name="borderColor" type="Color"/>
        <xs:attribute name="clipToBounds" type="Boolean"/>
        <xs:attribute name="borderCorner" type="TRBLValue"/>
        <xs:attribute name="layout" default="frame" type="LayoutMethod"/>
        <xs:attribute name="panoHeading" type="xs:float"/>
        <xs:attribute name="panoPitch" type="xs:float"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="ButtonAttributes">
        <xs:attribute name="text" type="xs:string"/>
        <xs:attribute name="fontColor" type="Color"/>
        <xs:attribute name="fontSize" type="Number"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="PanoViewAttributes">
        <xs:attribute name="panoId" type="xs:string"/>
        <xs:attribute name="heading" type="xs:float"/>
        <xs:attribute name="pitch" type="xs:float"/>
        <xs:attribute name="gravityEnable" type="Boolean"/>
        <xs:attribute name="zoom" type="xs:float"/>
        <xs:attribute name="VREnable" type="Boolean"/>
        <xs:attribute name="autoplayEnable" type="Boolean"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="Model3DViewAttributes">
        <xs:attribute name="sceneId" type="xs:string"/>
    </xs:attributeGroup>

    <xs:element name="include">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>

            <xs:attribute name="src" type="xs:string"/>
            <xs:attribute name="data" type="xs:string"/>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="View">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="ScannerView">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Model3DView">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="Model3DViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="PanoView">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="PanoViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="WebView">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attribute name="src" type="xs:string"/>
            <xs:attribute name="data" type="xs:string"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Page">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>


    <xs:element name="InputView">
        <xs:complexType>
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="FontAttributes"/>
            <xs:attribute name="hint" type="xs:string"/>
            <xs:attribute name="inputType" type="InputType"/>
            <xs:attribute name="text" type="xs:string"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>
    <xs:element name="TextAreaView">
        <xs:complexType>
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="FontAttributes"/>
            <xs:attribute name="hint" type="xs:string"/>
            <xs:attribute name="inputType" type="InputType"/>
            <xs:attribute name="text" type="xs:string"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ListView">
        <xs:complexType>
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ListViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>


    <xs:element name="PullToRefreshView">
        <xs:complexType>
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ListViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ToggleButtonGroup">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Button">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="ButtonAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="ToggleButton">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="ButtonAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="MapView">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>


    <xs:element name="ImageView">
        <xs:complexType>
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attribute name="src" type="xs:string"/>
            <xs:attribute name="crop" type="PXNumber"/>
            <xs:attribute name="stretchX" type="PXNumber"/>
            <xs:attribute name="stretchY" type="PXNumber"/>
            <xs:attribute name="stretchWidth" type="PXNumber"/>
            <xs:attribute name="stretchHeight" type="PXNumber"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="TextView">
        <xs:complexType>
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="FontAttributes"/>
            <xs:attribute name="text" type="xs:string"/>
            <xs:attribute name="lineSpace" type="Number"/>
            <xs:attribute name="wordSpace" type="Number"/>
            <xs:attribute name="html" type="xs:anyType"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="ScrollView">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ScrollViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:attributeGroup name="FontAttributes">
        <xs:attribute name="fontBold" type="Boolean"/>
        <xs:attribute name="fontSize" type="Number"/>
        <xs:attribute name="fontColor" type="Color"/>
    </xs:attributeGroup>


    <xs:attributeGroup name="ScrollViewAttributes">
        <xs:attributeGroup ref="ViewAttributes"/>
        <xs:attribute name="pageScrollEnable" type="Boolean"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="ListViewAttributes">
        <xs:attributeGroup ref="ScrollViewAttributes"/>
    </xs:attributeGroup>


</xs:schema>

=== Catfeeds/goodwxapp/shunde-master/ued/pano_admin/static/wx/Home.bundle/pages/NewPwdPage.xml
<?xml version="1.0"?>
<Page id="rootView"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../View.xsd"
      layout="frame"
      background="#F9F9F9">

    <View id="loginModule" layout="vertical">

        <View width="fill" height="wrap" >
            <View width="fill" height="wrap" layout="vertical">
                <View width="fill" height="44dp" background="#FFFFFF">
                    <ImageView src="../images/Logo_shot.svg" width="wrap" height="wrap" gravity="center" margin="12 0 12 0"/>
                </View>
                <View width="fill" height="1dp" background="#E5E5E5"/>
            </View>

            <View id="errorHintBox" background="#E64340" width="fill" height="35dp" visible="false">
                <TextView id="errorHint" width="wrap" height="wrap" text="两次密码不一致" fontSize="15dp" fontColor="#FFFFFF" gravity="center"/>
            </View>
        </View>

        <View width="fill" height="wrap" background="#FFFFFF" marginTop="16dp" layout="vertical">
            <View width="fill" height="1dp" background="#E5E5E5"/>

            <View id="newPwd" width="fill" height="wrap" layout="horizontal" >
                <TextView width="wrap" height="wrap" text="新密码" fontColor="#333333" fontSize="17dp"
                          margin="12 32 12 16"/>
                <InputView id="newPwdInput" width="fill" height="match" hint="请设置密码" inputType="password"/>
            </View>

            <View width="fill" height="1dp" marginLeft="16dp" background="#E5E5E5"/>

            <View id="newPwdConfirm" width="fill" height="wrap" layout="horizontal">
                <TextView width="wrap" height="wrap" text="确认密码" fontColor="#333333" fontSize="17dp"
                          margin="12 16 12 16"/>
                <InputView id="newPwdConfirmInput" width="fill" height="match" hint="请确认密码" inputType="password"/>
            </View>

            <View width="fill" height="1dp" background="#E5E5E5"/>
        </View>

        <View id="resetPwdBtn" width="fill" height="wrap" margin="24 16 0 16">
            <View background="#F15A3F" width="fill" height="48dp" borderCorner="6dp" clipToBounds="true"/>
            <View width="wrap" height="wrap" gravity="center">
                <TextView text="重置密码" width="wrap" height="wrap" fontSize="18dp" fontColor="#FFFFFF"/>
            </View>

            <View id="resetBtnCover" width="fill" height="48dp" background="#FFFFFF" alpha="0.4"/>

        </View>
    </View>


</Page>

=== Catfeeds/goodwxapp/shunde-master/ued/pano_pch5/static/wx/Home.bundle/pages/myAccount.xml
<?xml version="1.0"?>
<Page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../View.xsd"
      layout="vertical"
      background="#F9F9F9"

>
  <include src="myAccount.js"/>
  <TextView fontColor="#888888" height="wrap" width="wrap" fontSize="14dp" text="账户信息" margin="10dp 0 10dp 15dp"/>
  <View layout="vertical" padding="15dp" background="#ffffff" height="wrap">
    <View height="20dp" marginBottom="10dp" contentGravity="centerVertical">
      <TextView fontSize="14dp" fontColor="#888888" height="wrap" width="wrap" text="昵称"/>
      <TextView id="name" fontSize="14dp" fontColor="#888888" height="wrap" width="wrap" gravity="right" text=""/>
    </View>
    <View height="20dp" marginBottom="10dp" contentGravity="centerVertical">
      <TextView fontSize="14dp" fontColor="#888888" height="wrap" width="wrap" text="手机号"/>
      <TextView id="phone" fontSize="14dp" fontColor="#888888" height="wrap" width="wrap" gravity="right" text=""/>
    </View>
    <View height="20dp"  contentGravity="centerVertical">
      <TextView fontSize="14dp" fontColor="#888888" height="wrap" width="wrap" text="邮箱"/>
      <TextView id="e_mail" fontSize="14dp" fontColor="#888888" height="wrap" width="wrap" gravity="right" text=""/>
    </View>
  </View>
  <TextView id="logout" fontColor="#ffffff" fontSize="18dp" contentGravity="center" borderCorner="3dp" clipToBounds="true"
            background="#F15A3F" height="47dp" text="退出登录" width="match 0.89" gravity="centerHorizontal"
            marginTop="60dp"/>
</Page>

=== Catfeeds/goodwxapp/shunde-master/ued/pano_admin/static/wx/Home.bundle/pages/ConfirmSuccessPage.xml
<?xml version="1.0"?>
<Page id="rootView"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../View.xsd"
      layout="frame"
      background="#FFFFFF">

    <View layout="vertical">

        <View width="fill" height="wrap" layout="frame" padding="12 0 12 16" background="#FFFFFF">
            <ImageView id="btnBack" width="24dp" height="24dp" src="../images/ic_return.svg"/>
            <TextView id="taskName" text="瑞吉酒店" width="wrap" height="wrap" fontSize="17dp" fontColor="#333333" gravity="center"/>
        </View>
        <View width="fill" height="1dp" background="#E5E5E5"/>

        <View width="fill" height="wrap" background="#FFFFFF" marginTop="16dp" layout="vertical">

            <ImageView width="90dp" height="90dp" src="../images/success.svg" marginTop="75dp" gravity="centerHorizontal"/>

            <TextView width="wrap" height="wrap" text="确认成功" fontColor="#333333" fontSize="20dp"
                      margin="30 0 15 0" gravity="center"/>

            <TextView width="wrap" height="wrap" text="你的需求已确认拍摄完成" fontColor="#888888" fontSize="14dp"
                      margin="0 0 60 0" gravity="center"/>

        </View>

    </View>


</Page>

=== Catfeeds/goodwxapp/shunde-master/ued/pano_admin/static/wx/Home.bundle/pages/ForgetPwdPage.xml
<?xml version="1.0"?>
<Page id="rootView"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../View.xsd"
      layout="frame"
      background="#F9F9F9">

    <View layout="vertical">

        <View width="fill" height="wrap" >

            <View width="fill" height="wrap" layout="vertical">
                <View width="fill" height="44dp" background="#FFFFFF">
                    <ImageView src="../images/Logo_shot.svg" width="wrap" height="wrap" gravity="center" margin="12 0 12 0"/>
                </View>
                <View width="fill" height="1dp" background="#E5E5E5"/>
            </View>

            <View id="errorHintBox" background="#E64340" width="fill" height="35dp" visible="false">
                <TextView id="errorHint" width="wrap" height="wrap" text="验证码错误" fontSize="15dp" fontColor="#FFFFFF" gravity="center"/>
            </View>

        </View>

        <View width="fill" height="wrap" background="#FFFFFF" marginTop="16dp" layout="vertical">
            <View width="fill" height="1dp" background="#E5E5E5"/>

            <View id="phoneNum" width="fill" height="wrap" layout="frame" >
                <View layout="horizontal" width="fill" height="wrap">
                    <TextView width="wrap" height="wrap" text="国家/地区" fontColor="#333333" fontSize="16dp"
                              margin="12 14 12 16"/>
                    <TextView width="wrap" height="wrap" text="中国(+86)" fontColor="#333333" fontSize="16dp"
                              margin="12 16 12 0"/>
                </View>
                <ImageView width="8dp" height="14dp" src="../images/Chevron.svg" gravity="centerVertical|right" marginRight="16"/>

            </View>

            <View width="fill" height="1dp" marginLeft="16dp" background="#E5E5E5"/>

            <View id="phoneNum" width="fill" height="wrap" layout="horizontal" >
                <TextView width="wrap" height="wrap" text="手机号码" fontColor="#333333" fontSize="16dp" margin="12 20 12 16"/>
                <InputView id="phoneNumInput" width="fill" height="match" hint="填写手机号码"/>
                <View width="1dp" height="match" background="#E5E5E5"/>
                <TextView id="getVerifyCodeBtn" width="wrap" height="wrap" text="获取验证码" fontColor="#333333" fontSize="16dp" margin="10 12 12 10"/>
            </View>

            <View width="fill" height="1dp" marginLeft="16dp" background="#E5E5E5"/>

            <View id="verifyCode" width="fill" height="wrap" layout="horizontal">
                <TextView width="wrap" height="wrap" text="验证码" fontColor="#333333" fontSize="16dp"
                          margin="12 36 12 16"/>
                <InputView id="verifyCodeInput" width="fill" height="match" hint="请输入验证码"/>
            </View>

            <View width="fill" height="1dp" background="#E5E5E5"/>
        </View>

        <View id="nextBtn" width="fill" height="wrap"  margin="36 16 0 16">
            <View background="#F15A3F" width="fill" height="48dp" borderCorner="6dp" clipToBounds="true"/>
            <View width="wrap" height="wrap" gravity="center">
                <TextView text="下一步" width="wrap" height="wrap" fontSize="18dp" fontColor="#FFFFFF"/>
            </View>

            <View id="nextBtnCover" width="fill" height="48dp" background="#FFFFFF" alpha="0.4"/>

        </View>
    </View>


</Page>

=== Catfeeds/goodwxapp/shunde-master/ued/pano_admin/static/wx/Home.bundle/pages/TaskListPage.xml
<?xml version="1.0"?>
<Page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../View.xsd"
      layout="frame"
      background="#FFFFFF">

   <View layout="vertical">
     <!--内容页-->
     <View id="contentContainer" clipToBounds="true" height="fill">
       <!--我的任务-->
       <View id="myTask" layout="vertical"  marginTop="46dp">
         <View width="fill" height="wrap" padding="10 0 10 16" background="#F9F9F9">
           <TextView text="选择要开始处理的需求"  width="fill" height="wrap" fontSize="14dp" fontColor="#888888" />
         </View>
         <View width="fill" height="1dp" background="#E5E5E5"/>
         <View height="fill" clipToBounds="true">
           <ListView id="taskListView" width="fill" height="fill" background="#FFFFFF"/>
         </View>
       </View>
       <!--任务大厅-->
       <include id="myAccount" src="myAccount.xml" gone="true" marginTop="46dp"/>
       <!--我的账户-->
       <include id="taskHall" src="taskHall/page.xml" gone="true" marginTop="46dp"/>
     </View>

     <include id="bottomTab" src="BottomTab.xml"  gravity="bottom"/>
   </View>

    <View width="fill" height="wrap" layout="vertical">
        <View width="fill" height="44dp" background="#FFFFFF">
            <ImageView src="../images/Logo_shot.svg" width="wrap" height="wrap" gravity="center" margin="12 0 12 0"/>
        </View>
        <View width="fill" height="1dp" background="#E5E5E5"/>
    </View>

</Page>
