=== Catfeeds/goodwxapp/treasure_national-master/src/app.bundle/View.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <!-- common type defines -->
    <xs:simpleType name="Boolean">
        <xs:restriction base="xs:string">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="InputType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="text"/>
            <xs:enumeration value="number"/>
            <xs:enumeration value="password"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Color">
        <xs:restriction base="xs:string">
            <xs:pattern value="(\#[a-zA-Z0-9]{6}|\#[a-zA-Z0-9]{8})"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Number">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[\-]?[0-9]+(\.[0-9]+)?(dp|px)"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:double">
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>

    <xs:simpleType name="PXNumber">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[\-]?[0-9]+(\.[0-9]+)?px"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>

    <xs:simpleType name="Gravity">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="left"/>
                    <xs:enumeration value="top"/>
                    <xs:enumeration value="right"/>
                    <xs:enumeration value="bottom"/>
                    <xs:enumeration value="center"/>
                    <xs:enumeration value="centerHorizontal"/>
                    <xs:enumeration value="centerVertical"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern
                            value="(left|top|right|bottom|center|centerHorizontal|centerVertical)((\|)(left|top|right|bottom|center|centerHorizontal|centerVertical))+"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>

    </xs:simpleType>
    <xs:simpleType name="TRBLValue">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern
                            value="([\-]?[0-9]+(\.[0-9]+)?(dp|px)?)(\s[\-]?[0-9]+(\.[0-9]+)?(dp|px)?){0,3}"></xs:pattern>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
    <xs:simpleType name="WidthSpecLayoutConstrain">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="WidthLayoutConstrain"/>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern
                            value="(fill|match|wrap|matchHeight|([\-]?[0-9]+(\.[0-9]+)?[dDfF]?))(\s+)([\-]?[0-9]+(\.[0-9]+)?[dDfF]?)"></xs:pattern>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="Number">
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
    <xs:simpleType name="WidthLayoutConstrain">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="fill"/>
                    <xs:enumeration value="match"/>
                    <xs:enumeration value="wrap"/>
                    <xs:enumeration value="matchHeight"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:double">
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
    <xs:simpleType name="HeightSpecLayoutConstrain">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="HeightLayoutConstrain"/>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern
                            value="(fill|match|wrap|matchWidth|([\-]?[0-9]+(\.[0-9]+)?[dDfF]?))(\s+)([\-]?[0-9]+(\.[0-9]+)?[dDfF]?)"></xs:pattern>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
    <xs:simpleType name="HeightLayoutConstrain">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="fill"/>
                    <xs:enumeration value="match"/>
                    <xs:enumeration value="wrap"/>
                    <xs:enumeration value="matchWidth"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:double">
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="Number">
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>


    <xs:simpleType name="LayoutMethod">
        <xs:restriction base="xs:string">
            <xs:enumeration value="frame"/>
            <xs:enumeration value="vertical"/>
            <xs:enumeration value="horizontal"/>
            <xs:enumeration value="flow"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- common attributes -->


    <xs:group name="ViewGroup">
        <xs:choice>
            <xs:element ref="include"/>
            <xs:element ref="View"/>
            <xs:element ref="Page"/>
            <xs:element ref="ScrollView"/>
            <xs:element ref="ImageView"/>
            <xs:element ref="TextView"/>
            <xs:element ref="InputView"/>
            <xs:element ref="TextAreaView"/>
            <xs:element ref="ListView"/>
            <xs:element ref="PullToRefreshView"/>
            <xs:element ref="Button"/>
            <xs:element ref="ToggleButton"/>
            <xs:element ref="ToggleButtonGroup"/>
            <xs:element ref="MapView"/>
            <xs:element ref="WebView"/>
            <xs:element ref="PanoView"/>
            <xs:element ref="ScannerView"/>
            <xs:element ref="Model3DView"/>
        </xs:choice>
    </xs:group>

    <xs:attributeGroup name="ViewAttributes">
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="src" type="xs:string"/>
        <xs:attribute name="alpha" type="xs:float"/>
        <xs:attribute name="anchorX" type="xs:float"/>
        <xs:attribute name="anchorY" type="xs:float"/>
        <xs:attribute name="scaleX" type="xs:float"/>
        <xs:attribute name="scaleY" type="xs:float"/>
        <xs:attribute name="rotateX" type="xs:float"/>
        <xs:attribute name="rotateY" type="xs:float"/>
        <xs:attribute name="rotateZ" type="xs:float"/>
        <xs:attribute name="cameraDistance" type="Number"/>
        <xs:attribute name="visible" type="Boolean"/>
        <xs:attribute name="touchable" type="Boolean"/>
        <xs:attribute name="width" default="fill" type="WidthSpecLayoutConstrain"/>
        <xs:attribute name="height" default="fill" type="HeightSpecLayoutConstrain"/>
        <xs:attribute name="margin" type="TRBLValue"/>
        <xs:attribute name="marginTop" type="Number"/>
        <xs:attribute name="marginRight" type="Number"/>
        <xs:attribute name="marginLeft" type="Number"/>
        <xs:attribute name="marginBottom" type="Number"/>
        <xs:attribute name="padding" type="TRBLValue"/>
        <xs:attribute name="paddingTop" type="Number"/>
        <xs:attribute name="paddingRight" type="Number"/>
        <xs:attribute name="paddingLeft" type="Number"/>
        <xs:attribute name="paddingBottom" type="Number"/>
        <xs:attribute name="gravity" type="Gravity"/>
        <xs:attribute name="contentGravity" type="Gravity"/>
        <xs:attribute name="background" type="Color"/>
        <xs:attribute name="borderWidth" type="Number"/>
        <xs:attribute name="borderColor" type="Color"/>
        <xs:attribute name="clipToBounds" type="Boolean"/>
        <xs:attribute name="borderCorner" type="TRBLValue"/>
        <xs:attribute name="layout" default="frame" type="LayoutMethod"/>
        <xs:attribute name="panoHeading" type="xs:float"/>
        <xs:attribute name="panoPitch" type="xs:float"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="ButtonAttributes">
        <xs:attribute name="text" type="xs:string"/>
        <xs:attribute name="fontColor" type="Color"/>
        <xs:attribute name="fontSize" type="Number"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="PanoViewAttributes">
        <xs:attribute name="panoId" type="xs:string"/>
        <xs:attribute name="heading" type="xs:float"/>
        <xs:attribute name="pitch" type="xs:float"/>
        <xs:attribute name="gravityEnable" type="Boolean"/>
        <xs:attribute name="zoom" type="xs:float"/>
        <xs:attribute name="VREnable" type="Boolean"/>
        <xs:attribute name="autoplayEnable" type="Boolean"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="Model3DViewAttributes">
        <xs:attribute name="sceneId" type="xs:string"/>
    </xs:attributeGroup>

    <xs:element name="include">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>

            <xs:attribute name="src" type="xs:string"/>
            <xs:attribute name="data" type="xs:string"/>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="View">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="ScannerView">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Model3DView">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="Model3DViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="PanoView">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="PanoViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="WebView">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attribute name="src" type="xs:string"/>
            <xs:attribute name="data" type="xs:string"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Page">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>


    <xs:element name="InputView">
        <xs:complexType>
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="FontAttributes"/>
            <xs:attribute name="hint" type="xs:string"/>
            <xs:attribute name="inputType" type="InputType"/>
            <xs:attribute name="text" type="xs:string"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>
    <xs:element name="TextAreaView">
        <xs:complexType>
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="FontAttributes"/>
            <xs:attribute name="hint" type="xs:string"/>
            <xs:attribute name="inputType" type="InputType"/>
            <xs:attribute name="text" type="xs:string"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ListView">
        <xs:complexType>
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ListViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>


    <xs:element name="PullToRefreshView">
        <xs:complexType>
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ListViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ToggleButtonGroup">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Button">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="ButtonAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="ToggleButton">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="ButtonAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="MapView">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>


    <xs:element name="ImageView">
        <xs:complexType>
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attribute name="src" type="xs:string"/>
            <xs:attribute name="crop" type="PXNumber"/>
            <xs:attribute name="stretchX" type="PXNumber"/>
            <xs:attribute name="stretchY" type="PXNumber"/>
            <xs:attribute name="stretchWidth" type="PXNumber"/>
            <xs:attribute name="stretchHeight" type="PXNumber"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="TextView">
        <xs:complexType>
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="FontAttributes"/>
            <xs:attribute name="text" type="xs:string"/>
            <xs:attribute name="lineSpace" type="Number"/>
            <xs:attribute name="wordSpace" type="Number"/>
            <xs:attribute name="html" type="xs:anyType"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="ScrollView">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ScrollViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:attributeGroup name="FontAttributes">
        <xs:attribute name="fontBold" type="Boolean"/>
        <xs:attribute name="fontSize" type="Number"/>
        <xs:attribute name="fontColor" type="Color"/>
    </xs:attributeGroup>


    <xs:attributeGroup name="ScrollViewAttributes">
        <xs:attributeGroup ref="ViewAttributes"/>
        <xs:attribute name="pageScrollEnable" type="Boolean"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="ListViewAttributes">
        <xs:attributeGroup ref="ScrollViewAttributes"/>
    </xs:attributeGroup>


</xs:schema>

=== Catfeeds/goodwxapp/shunde-master/ued/pano_pch5/static/wx/Home.bundle/pages/TaskDetailPage.xml
<?xml version="1.0"?>
<Page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../View.xsd"
      layout="frame"
      background="#F9F9F9">

    <View width="fill" height="fill">

        <View width="fill" height="fill" layout="vertical" background="#F9F9F9">
            <View width="fill" height="wrap" layout="frame" padding="12 0 12 16" background="#FFFFFF">
                <ImageView id="btnBack" width="24dp" height="24dp" src="../images/ic_return.svg"/>
                <TextView id="taskName" text="瑞吉酒店" width="wrap" height="wrap" fontSize="17dp" fontColor="#333333" gravity="center"/>
            </View>

            <View width="fill" height="1dp" background="#dcdcdc"/>
            <TextView text="联系信息"  width="fill" height="wrap" fontSize="14dp" fontColor="#888888" margin="10 0 10 16"/>
            <View width="fill" height="1dp" background="#dcdcdc"/>

            <View width="fill" height="wrap" background="#FFFFFF" padding="9 16 9 10">
                <View width="wrap" height="wrap" layout="horizontal">
                    <ImageView id="avtarImg" width="50dp" height="50dp" src="../images/default_Avatar.svg" marginRight="10dp"/>
                    <View width="wrap" height="wrap" layout="vertical" gravity="centerVertical">
                        <TextView id="photographerName" width="wrap" height="wrap" text="谢秀春" fontSize="17dp" fontColor="#333333" marginBottom="10dp"/>
                        <TextView id="photographerPhone" width="wrap" height="wrap" text="13565644345" fontSize="14dp" fontColor="#888888" />
                    </View>
                </View>
                <ImageView  id="callBtn" width="24dp" height="24dp" src="../images/phone.svg" gravity="centerVertical|right" />
            </View>
          <View width="fill" height="1dp" background="#dcdcdc" marginBottom="20dp"/>

          <View height="45dp" background="#F9F9F9" contentGravity="centerVertical" padding="15dp 10dp 15dp 10dp" gone="true">
              <TextView id="shotCount" fontColor="#555555" fontSize="16dp" height="wrap"/>
              <View id="toMap" height="wrap" width="wrap" gravity="right" layout="horizontal">
                <ImageView src="../images/map_hl_24px.svg" height="24dp" width="24dp"/>
                <TextView fontColor="#F15A3F" fontSize="16dp" height="wrap" width="wrap" gravity="centerVertical" text="地图"/>
              </View>
          </View>

            <View layout="vertical" id="spotsDatail">
              <View id="forHotel" gone="true" layout="vertical" height="wrap" background="#ffffff">
                <View width="fill" height="1dp" background="#dcdcdc"/>
                <TextView id="spotName" fontColor="#333333" height="wrap" fontSize="18dp" margin="20dp 15dp 0dp 15dp" text="拍摄点名称"/>
                <View id="photographerAddressBox" margin="15dp 15dp 20dp 10dp" width="fill" height="wrap" background="#FFFFFF">
                  <View width="fill" height="wrap" layout="horizontal" gravity="centerVertical">
                    <ImageView width="24dp" height="24dp" src="../images/ic_place_24px.svg"/>
                    <TextView id="photographerAddress" width="fill" height="wrap" text="天津市河东区团结路57号" fontSize="14dp" fontColor="#4A90E2" gravity="centerVertical"/>
                  </View>
                </View>
                <TextView id="tv_waiguan" fontColor="#333333" height="wrap" fontSize="18dp" margin="20dp 15dp 10dp 15dp" text="外观" gone="false"/>
                <View width="fill" height="0.5dp" background="#e6e6e6"/>
                <View id="container" height="wrap" layout="flow"/>
<!--                <include src="item.xml" data="{'content':'景区外观'}"/>-->
                <!--<TextView text="拍摄清单"  width="fill" height="wrap" fontSize="14dp" fontColor="#888888" margin="0 15 10 15"/>-->

              </View>
              <View width="fill" clipToBounds="true" background="#F9F9F9" marginBottom="80dp">
                <ScrollView id="facilityListView" width="fill" layout="vertical"/>
              </View>
            </View>

            <View width="fill" gone="true" height="wrap" marginTop="12dp" marginBottom="80dp">
                <TextView id="facilityCount" width="wrap" height="wrap" text="共有7个设施点" fontSize="13dp" fontColor="#999999" gravity="right" marginRight="10dp"/>
            </View>

        </View>

        <include id="map" src="map.xml" gone="true" background="#cc000000" />

        <View id="completePhotographBtn" width="fill" height="55dp" background="#F15A3F" gravity="bottom">
            <View width="wrap" height="wrap" layout="horizontal" gravity="center">
                <TextView id="photographStatus" text="完成拍摄" fontSize="18dp" fontColor="#FFFFFF" width="wrap" height="wrap"/>
                <ImageView id="taskQrCode" width="18dp" height="18dp" src="../images/qr_Code@2x.png" gone="true" marginLeft="6dp"/>
            </View>
            <View id="photographBtnCover" width="fill" height="55dp" background="#FFFFFF" alpha="0.4"/>
        </View>

    </View>

    <View id="qrcodeDialog" layout="frame" width="fill" height="fill"  contentGravity="center" visible="false">

        <View id="qrcodeDialogCover" width="fill" height="fill" background="#000000" alpha="0.5"/>

        <View width="wrap" height="wrap" layout="vertical" >
            <View width="335dp" height="wrap" layout="vertical" padding="40 40 25 40" borderCorner="6dp" clipToBounds="true" background="#FFFFFF">
                <TextView id="qrTaskName" width="wrap" height="wrap" text="瑞吉酒店" fontSize="24dp" fontColor="#333333" marginBottom="10dp"/>

                <TextView id="qrTaskAddress" width="fill" height="wrap" text="我是一个省市区信息" fontSize="14dp" fontColor="#888888" marginBottom="28dp"/>

                <View id="qrImg" width="255dp" height="255dp" marginBottom="20dp">
                </View>

                <TextView width="wrap" height="wrap" text="需求方扫码确认拍摄完成即可开始制作" fontSize="14dp" fontColor="#888888" gravity="centerHorizontal"/>

            </View>

            <ImageView id="qrClose" width="40dp" height="40dp" src="../images/close@2x.png" gravity="centerHorizontal"
                       marginTop="20dp"/>
        </View>

    </View>


    <View id="confirmDialog" visible="false" width="fill" height="fill" contentGravity="centerHorizontal">
        <View id="confirmDialogCover" width="fill" height="fill" background="#000000" alpha="0.5"/>
        <View width="fill" height="wrap" gravity="bottom" layout="vertical" background="#F9F9F9">
            <View width="fill" height="wrap" background="#FFFFFF" layout="vertical">
                <TextView width="wrap" height="wrap" fontSize="14dp" fontColor="#888888"  gravity="center" margin="24 0 24 0" text="确认完成之后，你将不能修改酒店设施信息"/>
                <View width="fill" height="1dp" background="#E5E5E5"/>
                <TextView id="confirmCompletedBtn" width="wrap" height="wrap" fontSize="18dp" fontColor="#E64340" text="确认完成拍摄" margin="24 0 24 0" gravity="center"/>
            </View>

            <View width="fill" height="wrap" background="#FFFFFF" marginTop="6dp" padding="24 0 24 0">
                <TextView id="cancelBtn" width="wrap" height="wrap" fontSize="18dp" fontColor="#333333" text="取消" gravity="center"/>
            </View>

        </View>
    </View>



</Page>
