=== Catfeeds/goodwxapp/treasure_national-master/src/app.bundle/View.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <!-- common type defines -->
    <xs:simpleType name="Boolean">
        <xs:restriction base="xs:string">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="InputType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="text"/>
            <xs:enumeration value="number"/>
            <xs:enumeration value="password"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Color">
        <xs:restriction base="xs:string">
            <xs:pattern value="(\#[a-zA-Z0-9]{6}|\#[a-zA-Z0-9]{8})"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Number">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[\-]?[0-9]+(\.[0-9]+)?(dp|px)"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:double">
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>

    <xs:simpleType name="PXNumber">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[\-]?[0-9]+(\.[0-9]+)?px"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>

    <xs:simpleType name="Gravity">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="left"/>
                    <xs:enumeration value="top"/>
                    <xs:enumeration value="right"/>
                    <xs:enumeration value="bottom"/>
                    <xs:enumeration value="center"/>
                    <xs:enumeration value="centerHorizontal"/>
                    <xs:enumeration value="centerVertical"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern
                            value="(left|top|right|bottom|center|centerHorizontal|centerVertical)((\|)(left|top|right|bottom|center|centerHorizontal|centerVertical))+"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>

    </xs:simpleType>
    <xs:simpleType name="TRBLValue">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern
                            value="([\-]?[0-9]+(\.[0-9]+)?(dp|px)?)(\s[\-]?[0-9]+(\.[0-9]+)?(dp|px)?){0,3}"></xs:pattern>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
    <xs:simpleType name="WidthSpecLayoutConstrain">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="WidthLayoutConstrain"/>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern
                            value="(fill|match|wrap|matchHeight|([\-]?[0-9]+(\.[0-9]+)?[dDfF]?))(\s+)([\-]?[0-9]+(\.[0-9]+)?[dDfF]?)"></xs:pattern>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="Number">
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
    <xs:simpleType name="WidthLayoutConstrain">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="fill"/>
                    <xs:enumeration value="match"/>
                    <xs:enumeration value="wrap"/>
                    <xs:enumeration value="matchHeight"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:double">
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
    <xs:simpleType name="HeightSpecLayoutConstrain">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="HeightLayoutConstrain"/>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern
                            value="(fill|match|wrap|matchWidth|([\-]?[0-9]+(\.[0-9]+)?[dDfF]?))(\s+)([\-]?[0-9]+(\.[0-9]+)?[dDfF]?)"></xs:pattern>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
    <xs:simpleType name="HeightLayoutConstrain">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="fill"/>
                    <xs:enumeration value="match"/>
                    <xs:enumeration value="wrap"/>
                    <xs:enumeration value="matchWidth"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:double">
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="Number">
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>


    <xs:simpleType name="LayoutMethod">
        <xs:restriction base="xs:string">
            <xs:enumeration value="frame"/>
            <xs:enumeration value="vertical"/>
            <xs:enumeration value="horizontal"/>
            <xs:enumeration value="flow"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- common attributes -->


    <xs:group name="ViewGroup">
        <xs:choice>
            <xs:element ref="include"/>
            <xs:element ref="View"/>
            <xs:element ref="Page"/>
            <xs:element ref="ScrollView"/>
            <xs:element ref="ImageView"/>
            <xs:element ref="TextView"/>
            <xs:element ref="InputView"/>
            <xs:element ref="TextAreaView"/>
            <xs:element ref="ListView"/>
            <xs:element ref="PullToRefreshView"/>
            <xs:element ref="Button"/>
            <xs:element ref="ToggleButton"/>
            <xs:element ref="ToggleButtonGroup"/>
            <xs:element ref="MapView"/>
            <xs:element ref="WebView"/>
            <xs:element ref="PanoView"/>
            <xs:element ref="ScannerView"/>
            <xs:element ref="Model3DView"/>
        </xs:choice>
    </xs:group>

    <xs:attributeGroup name="ViewAttributes">
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="src" type="xs:string"/>
        <xs:attribute name="alpha" type="xs:float"/>
        <xs:attribute name="anchorX" type="xs:float"/>
        <xs:attribute name="anchorY" type="xs:float"/>
        <xs:attribute name="scaleX" type="xs:float"/>
        <xs:attribute name="scaleY" type="xs:float"/>
        <xs:attribute name="rotateX" type="xs:float"/>
        <xs:attribute name="rotateY" type="xs:float"/>
        <xs:attribute name="rotateZ" type="xs:float"/>
        <xs:attribute name="cameraDistance" type="Number"/>
        <xs:attribute name="visible" type="Boolean"/>
        <xs:attribute name="touchable" type="Boolean"/>
        <xs:attribute name="width" default="fill" type="WidthSpecLayoutConstrain"/>
        <xs:attribute name="height" default="fill" type="HeightSpecLayoutConstrain"/>
        <xs:attribute name="margin" type="TRBLValue"/>
        <xs:attribute name="marginTop" type="Number"/>
        <xs:attribute name="marginRight" type="Number"/>
        <xs:attribute name="marginLeft" type="Number"/>
        <xs:attribute name="marginBottom" type="Number"/>
        <xs:attribute name="padding" type="TRBLValue"/>
        <xs:attribute name="paddingTop" type="Number"/>
        <xs:attribute name="paddingRight" type="Number"/>
        <xs:attribute name="paddingLeft" type="Number"/>
        <xs:attribute name="paddingBottom" type="Number"/>
        <xs:attribute name="gravity" type="Gravity"/>
        <xs:attribute name="contentGravity" type="Gravity"/>
        <xs:attribute name="background" type="Color"/>
        <xs:attribute name="borderWidth" type="Number"/>
        <xs:attribute name="borderColor" type="Color"/>
        <xs:attribute name="clipToBounds" type="Boolean"/>
        <xs:attribute name="borderCorner" type="TRBLValue"/>
        <xs:attribute name="layout" default="frame" type="LayoutMethod"/>
        <xs:attribute name="panoHeading" type="xs:float"/>
        <xs:attribute name="panoPitch" type="xs:float"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="ButtonAttributes">
        <xs:attribute name="text" type="xs:string"/>
        <xs:attribute name="fontColor" type="Color"/>
        <xs:attribute name="fontSize" type="Number"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="PanoViewAttributes">
        <xs:attribute name="panoId" type="xs:string"/>
        <xs:attribute name="heading" type="xs:float"/>
        <xs:attribute name="pitch" type="xs:float"/>
        <xs:attribute name="gravityEnable" type="Boolean"/>
        <xs:attribute name="zoom" type="xs:float"/>
        <xs:attribute name="VREnable" type="Boolean"/>
        <xs:attribute name="autoplayEnable" type="Boolean"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="Model3DViewAttributes">
        <xs:attribute name="sceneId" type="xs:string"/>
    </xs:attributeGroup>

    <xs:element name="include">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>

            <xs:attribute name="src" type="xs:string"/>
            <xs:attribute name="data" type="xs:string"/>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="View">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="ScannerView">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Model3DView">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="Model3DViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="PanoView">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="PanoViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="WebView">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attribute name="src" type="xs:string"/>
            <xs:attribute name="data" type="xs:string"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Page">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>


    <xs:element name="InputView">
        <xs:complexType>
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="FontAttributes"/>
            <xs:attribute name="hint" type="xs:string"/>
            <xs:attribute name="inputType" type="InputType"/>
            <xs:attribute name="text" type="xs:string"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>
    <xs:element name="TextAreaView">
        <xs:complexType>
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="FontAttributes"/>
            <xs:attribute name="hint" type="xs:string"/>
            <xs:attribute name="inputType" type="InputType"/>
            <xs:attribute name="text" type="xs:string"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ListView">
        <xs:complexType>
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ListViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>


    <xs:element name="PullToRefreshView">
        <xs:complexType>
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ListViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ToggleButtonGroup">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Button">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="ButtonAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="ToggleButton">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="ButtonAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="MapView">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>


    <xs:element name="ImageView">
        <xs:complexType>
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attribute name="src" type="xs:string"/>
            <xs:attribute name="crop" type="PXNumber"/>
            <xs:attribute name="stretchX" type="PXNumber"/>
            <xs:attribute name="stretchY" type="PXNumber"/>
            <xs:attribute name="stretchWidth" type="PXNumber"/>
            <xs:attribute name="stretchHeight" type="PXNumber"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="TextView">
        <xs:complexType>
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ViewAttributes"/>
            <xs:attributeGroup ref="FontAttributes"/>
            <xs:attribute name="text" type="xs:string"/>
            <xs:attribute name="lineSpace" type="Number"/>
            <xs:attribute name="wordSpace" type="Number"/>
            <xs:attribute name="html" type="xs:anyType"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:element name="ScrollView">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:group ref="ViewGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="ScrollViewAttributes"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>

    <xs:attributeGroup name="FontAttributes">
        <xs:attribute name="fontBold" type="Boolean"/>
        <xs:attribute name="fontSize" type="Number"/>
        <xs:attribute name="fontColor" type="Color"/>
    </xs:attributeGroup>


    <xs:attributeGroup name="ScrollViewAttributes">
        <xs:attributeGroup ref="ViewAttributes"/>
        <xs:attribute name="pageScrollEnable" type="Boolean"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="ListViewAttributes">
        <xs:attributeGroup ref="ScrollViewAttributes"/>
    </xs:attributeGroup>


</xs:schema>

=== Catfeeds/goodwxapp/shunde-master/ued/pano_admin/static/wx/Home.bundle/main.xml
<?xml version="1.0"?>
<Page id="rootView"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="View.xsd"
      layout="frame"
      background="#F9F9F9">

    <View id="loginModule" layout="vertical">

        <View width="fill" height="wrap" >

            <View width="fill" height="wrap" layout="vertical">
                <View width="fill" height="44dp" background="#FFFFFF">
                    <ImageView src="images/Logo_shot.svg" width="wrap" height="wrap" gravity="center" margin="12 0 12 0"/>
                </View>
                <View width="fill" height="1dp" background="#E5E5E5"/>
            </View>

            <View id="errorHintBox" background="#E64340" width="fill" height="35dp" visible="false">
                <TextView id="errorHint" width="wrap" height="wrap" text="密码或者用户名不能为空" fontSize="15dp" fontColor="#FFFFFF" gravity="center"/>
            </View>

        </View>

        <View width="fill" height="wrap" background="#FFFFFF" marginTop="16dp" layout="vertical">
            <View width="fill" height="1dp" background="#E5E5E5"/>

            <View id="username" width="fill" height="wrap" layout="horizontal" >
                <TextView width="wrap" height="wrap" text="用户名" fontColor="#333333" fontSize="17dp"
                          margin="12 16 12 16"/>
                <InputView id="usernameInput" width="fill" height="match" hint="请输入用户名"/>
            </View>

            <View width="fill" height="1dp" marginLeft="16dp" background="#E5E5E5"/>

            <View id="password" width="fill" height="wrap" layout="horizontal">
                <TextView width="wrap" height="wrap" text="密码" fontColor="#333333" fontSize="17dp"
                          margin="12 32 12 16"/>
                <InputView id="passwordInput" width="fill" height="match" hint="请输入密码" inputType="password"/>
            </View>

            <View width="fill" height="1dp" background="#E5E5E5"/>
        </View>

        <TextView id="forgetPwdBtn" width="wrap" height="wrap" text="忘记密码" fontColor="#54ADDA" fontSize="14dp" margin="16 0 0 16"/>

        <View id="loginBtn" width="fill" height="wrap" margin="36 16 0 16" >
            <View background="#F15A3F" width="fill" height="48dp" borderCorner="6dp" clipToBounds="true"/>
            <View width="wrap" height="wrap" gravity="center">
                <TextView text="登录" width="wrap" height="wrap" fontSize="18dp" fontColor="#FFFFFF"/>
            </View>

            <View id="loginBtnCover" width="fill" height="48dp" background="#FFFFFF" alpha="0.4"/>

        </View>
    </View>


</Page>

=== Catfeeds/goodwxapp/shunde-master/ued/pano_admin/static/wx/Home.bundle/pages/FindPwdSuccess.xml
<?xml version="1.0"?>
<Page id="rootView"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../View.xsd"
      layout="frame"
      background="#F9F9F9">

    <View id="loginModule" layout="vertical">

        <View width="fill" height="44dp" background="#FFFFFF">
            <ImageView src="../images/Logo_shot.svg" width="wrap" height="wrap" gravity="center" margin="12 0 12 0"/>
        </View>
        <View width="fill" height="1dp" background="#E5E5E5"/>

        <View width="fill" height="wrap" background="#FFFFFF" marginTop="16dp" layout="vertical">

            <ImageView width="90dp" height="90dp" src="../images/success.svg" marginTop="75dp" gravity="centerHorizontal"/>

            <TextView width="wrap" height="wrap" text="重置成功" fontColor="#333333" fontSize="20dp"
                          margin="30 0 15 0" gravity="center"/>

            <TextView width="wrap" height="wrap" text="密码重置成功, 直接登录继续操作" fontColor="#888888" fontSize="14dp"
                      margin="0 0 60 0" gravity="center"/>

        </View>

        <View id="goLoginBtn" width="fill" height="wrap" margin="0 16 0 16">
            <View background="#F15A3F" width="fill" height="48dp" borderCorner="6dp" clipToBounds="true"/>
            <View width="wrap" height="wrap" gravity="center">
                <TextView text="去登陆" width="wrap" height="wrap" fontSize="18dp" fontColor="#FFFFFF"/>
            </View>

        </View>
    </View>


</Page>

=== Catfeeds/goodwxapp/shunde-master/ued/pano_pch5/static/wx/Home.bundle/pages/taskHall/cell.xml
<?xml version="1.0"?>
<View xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../View.xsd"
      layout="vertical"
      height="wrap"
      background="#ffffff">

  <include src="cell.js"/>

  <View layout="frame" height="wrap" padding="15dp">

      <View layout="vertical" gravity="left" height="wrap" width="wrap">

            <!--瑞吉酒店-->
            <TextView id="tv_title" width="wrap" height="wrap" fontSize="17dp" fontColor="#363636" fontBold="true" marginBottom="8dp"/>

            <!--地点-->
            <View layout="horizontal"  height="wrap" marginBottom="8dp" marginLeft="-3dp">

                <!--地点图标-->
                <ImageView height="20dp" width="20dp" src="../../images/ic_place_24px.svg"/>

                <!--地点信息-->
                <TextView id="tv_adr" fontSize="14dp" fontColor="#7F8389" height="wrap" width="wrap"/>

            </View>

            <!--已申请-->
            <View layout="horizontal" height="wrap">

                <!--已申请前缀-->
                <TextView text="已申请：" width="wrap" height="wrap" fontColor="#7F8389"/>

                <!--已申请数量-->
                <TextView id="tv_shenqin_count" fontColor="#F15A3F"/>

            </View>

      </View>

      <View layout="vertical"  gravity="right"  width="wrap" height="wrap">

            <!--点位-->
            <View layout="horizontal" height="wrap" contentGravity="centerVertical" marginBottom="10dp">

                <!--点位数量-->
                <TextView id="tv_dianwei_count" fontColor="#F15A3F" width="wrap" height="wrap" fontSize="18dp" fontBold="true" paddingRight="5dp"/>

                <!--点位后缀-->
                <TextView text="点位" height="wrap" width="wrap" fontColor="#7F8389"/>

            </View>

            <!--时间-->
            <TextView id="tv_time" width="wrap" height="wrap" fontColor="#7F8389"/>

      </View>

  </View>

  <View  height="1dp" background="#dddddd"/>


</View>

=== Catfeeds/goodwxapp/shunde-master/ued/pano_pch5/static/wx/Home.bundle/pages/FacilityListCell_album.xml
<?xml version="1.0"?>
<View xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../View.xsd"
      layout="vertical"
      width="fill"
      height="wrap"
      contentGravity="centerVertical"
      id="facilityCellRootView"
      background="#ffffff"
      marginBottom="10dp">
  <View width="fill" height="1dp" background="#dcdcdc"/>
  <View width="wrap" height="wrap" layout="horizontal" margin="20dp 15dp 15dp 15dp" >
    <TextView id="facilityName" width="wrap" height="wrap" fontSize="18dp" fontColor="#333333" marginRight="4dp"/>
    <TextView id="facilityNum" width="wrap" height="wrap" fontSize="18dp" fontColor="#333333" />
  </View>

  <View layout="horizontal" height="wrap" margin="0dp 15dp 20dp 15dp">
    <ImageView height="20dp" width="20dp" src="../images/ic_place_24px.svg"/>
    <TextView id="address" fontSize="14dp" fontColor="#4A90E2" height="wrap"/>
  </View>

  <TextView text="拍摄清单" fontSize="14dp" fontColor="#888888" margin="0dp 15dp 10dp 15dp" height="wrap"/>
  <View height="1dp" background="#e5e5e5" marginBottom="13dp"/>

  <ScrollView id="facilityBox" width="fill" height="wrap" margin="0dp 15dp 40dp 15dp" layout="horizontal"/>
  <View width="fill" height="1dp" background="#dcdcdc"/>
</View>

=== Catfeeds/goodwxapp/shunde-master/ued/pano_pch5/static/wx/Home.bundle/pages/taskHall/page.xml
<?xml version="1.0"?>
<Page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../View.xsd"
      layout="frame"
      background="#F9F9F9">

      <include src="page.js"/>

      <View layout="vertical">

        <View id="view_sort_container" height="wrap"/>

        <View layout="frame">

            <View clipToBounds="true">
              <ScrollView id="sv" layout="vertical"/>
            </View>

            <View id="view_top_sheet_container" />
        </View>


      </View>



</Page>
